### ISSUE TITLE
GemRB 9.2 update request.

### ISSUE THREAD

**Issue by Fernside2** [kloptops/Portmaster-misc#2]
Please update Arkos port for GemRB, and Portmaster, to GemRB 9.2, if possible.

Thanks for all your hard work.

**Comment by kloptops** [comment]
I will check it out this weekend and do a build for it. 👍

**Comment by kloptops** [comment]
@Fernside2 i have updated it to the latest github build, [download it from here](https://github.com/kloptops/Portmaster-misc/blob/main/releases/GemRB.zip).

If you use discord you can join the PortMaster github, we have a thread for this build if you want to give feedback here: [GemRB Testing](https://discord.com/channels/1122861252088172575/1149642310003478528) in the [PortMaster discord server](https://discord.gg/SbVcUM4qFp)

**Comment by Fernside2** [comment]
Amazing, will test over weekend. Thanks a lot.
